<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-09T19:47:42 IST" name="E-commerce Website Automation Test" finished-at="2024-07-09T19:47:46 IST" duration-ms="4367">
    <groups>
    </groups>
    <test started-at="2024-07-09T19:47:42 IST" name="Authorization" finished-at="2024-07-09T19:47:46 IST" duration-ms="4367">
      <class name="baseClases.SetUp">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:baseClases.SetUp@3857f613]" started-at="2024-07-09T19:47:36 IST" name="setUp" finished-at="2024-07-09T19:47:42 IST" duration-ms="5654" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:baseClases.SetUp@3857f613]" started-at="2024-07-09T19:47:47 IST" name="tearDown" finished-at="2024-07-09T19:47:49 IST" duration-ms="2676" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- baseClases.SetUp -->
      <class name="authentication.Login">
        <test-method is-config="true" signature="SetUpSuit()[pri:0, instance:authentication.Login@fbd1f6]" started-at="2024-07-09T19:47:42 IST" name="SetUpSuit" finished-at="2024-07-09T19:47:42 IST" duration-ms="29" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpSuit -->
        <test-method signature="tC_01test_passed()[pri:0, instance:authentication.Login@fbd1f6]" started-at="2024-07-09T19:47:42 IST" name="tC_01test_passed" finished-at="2024-07-09T19:47:45 IST" duration-ms="2505" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tC_01test_passed -->
        <test-method signature="tC_02test_Failed()[pri:0, instance:authentication.Login@fbd1f6]" started-at="2024-07-09T19:47:45 IST" name="tC_02test_Failed" finished-at="2024-07-09T19:47:45 IST" duration-ms="133" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[java.lang.AssertionError]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: java.lang.AssertionError
at baseClases.Helper.triggerAssertFail(Helper.java:112)
at authentication.Login.tC_02test_Failed(Login.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.AssertionError
at authentication.Login.tC_02test_Failed(Login.java:55)
... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tC_02test_Failed -->
        <test-method signature="tC_03test_Failed1()[pri:0, instance:authentication.Login@fbd1f6]" started-at="2024-07-09T19:47:45 IST" name="tC_03test_Failed1" finished-at="2024-07-09T19:47:45 IST" duration-ms="304" status="FAIL">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[java.lang.Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: java.lang.Exception
at baseClases.Helper.triggerExceptionFail(Helper.java:131)
at authentication.Login.tC_03test_Failed1(Login.java:72)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.Exception
at authentication.Login.tC_03test_Failed1(Login.java:70)
... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tC_03test_Failed1 -->
        <test-method signature="tC_04test_Skip()[pri:0, instance:authentication.Login@fbd1f6]" started-at="2024-07-09T19:47:45 IST" name="tC_04test_Skip" finished-at="2024-07-09T19:47:45 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tC_04test_Skip -->
        <test-method signature="tc_05PomTest()[pri:0, instance:authentication.Login@fbd1f6]" started-at="2024-07-09T19:47:45 IST" name="tc_05PomTest" finished-at="2024-07-09T19:47:46 IST" duration-ms="1313" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc_05PomTest -->
      </class> <!-- authentication.Login -->
    </test> <!-- Authorization -->
  </suite> <!-- E-commerce Website Automation Test -->
</testng-results>
